meta_product_name: "Zenkey"
meta_title: "Zenkey - La location n'a jamais été aussi facile"
meta_description: "Zenkey est un outil destiné aux propriétaires de biens locatifs, afin de leurs permettre de simplifier l'organisation des visites et la recherche d'un locataire"
meta_image: "background.jpg"                       # should exist in `app/assets/images/`
